"""REINFORCE agent - vanilla policy gradient algorithm.

This is the simplest policy gradient method and a great starting point for learning RL.

Key concepts:
- Policy gradient: directly optimize policy to maximize expected return
- Monte Carlo: use full episode returns (no bootstrapping)
- On-policy: learn from episodes generated by current policy
"""

import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from typing import Dict, List, Tuple

from agents.base import Agent
from utils.networks import PolicyNetwork, to_tensor


class REINFORCEAgent(Agent):
    """REINFORCE (Monte Carlo Policy Gradient) agent.

    Algorithm:
    1. Collect full episode using current policy
    2. Compute returns (cumulative discounted rewards)
    3. Update policy to increase probability of high-return actions
    """

    def __init__(
        self,
        state_dim: int,
        action_dim: int,
        hidden_dims: List[int] = [128, 128],
        learning_rate: float = 1e-3,
        gamma: float = 0.99,
        device: str = 'cpu'
    ):
        """Initialize REINFORCE agent.

        Args:
            state_dim: Dimension of state space
            action_dim: Number of discrete actions
            hidden_dims: Hidden layer dimensions for policy network
            learning_rate: Learning rate for optimizer
            gamma: Discount factor for returns
            device: Device to run on ('cpu' or 'cuda')
        """
        super().__init__(state_dim, action_dim)

        self.gamma = gamma
        self.device = device

        # Policy network
        self.policy = PolicyNetwork(state_dim, action_dim, hidden_dims).to(device)
        self.optimizer = optim.Adam(self.policy.parameters(), lr=learning_rate)

        # Episode buffer (stores transitions for current episode)
        self.episode_states: List[np.ndarray] = []
        self.episode_actions: List[int] = []
        self.episode_rewards: List[float] = []

    def act(self, state: np.ndarray, training: bool = True) -> int:
        """Select action using current policy.

        Args:
            state: Current state
            training: Whether in training mode (affects exploration)

        Returns:
            Selected action (integer)
        """
        state_tensor = to_tensor(state, self.device).unsqueeze(0)  # Add batch dimension

        with torch.no_grad():
            action_probs = self.policy.get_action_probs(state_tensor)

        # Sample action from policy distribution
        if training:
            action_dist = torch.distributions.Categorical(action_probs)
            action = action_dist.sample().item()
        else:
            # Greedy action for evaluation
            action = action_probs.argmax().item()

        return action

    def learn(
        self,
        state: np.ndarray,
        action: int,
        reward: float,
        next_state: np.ndarray,
        done: bool
    ) -> Dict[str, float]:
        """Store transition and update policy at end of episode.

        Args:
            state: Current state
            action: Action taken
            reward: Reward received
            next_state: Next state (unused in REINFORCE)
            done: Whether episode terminated

        Returns:
            Dictionary of metrics (empty if episode not done, loss if done)
        """
        # Store transition
        self.episode_states.append(state)
        self.episode_actions.append(action)
        self.episode_rewards.append(reward)

        # Only update at end of episode
        if not done:
            return {}

        # Compute returns (cumulative discounted rewards)
        returns = self._compute_returns(self.episode_rewards)

        # Convert to tensors
        states = to_tensor(np.array(self.episode_states), self.device)
        actions = torch.LongTensor(self.episode_actions).to(self.device)
        returns = to_tensor(returns, self.device)

        # Normalize returns (reduces variance)
        returns = (returns - returns.mean()) / (returns.std() + 1e-8)

        # Compute policy gradient loss
        action_probs = self.policy.get_action_probs(states)
        selected_action_probs = action_probs.gather(1, actions.unsqueeze(1)).squeeze()

        # Loss = -log(prob) * return (negative because we want to maximize)
        loss = -(torch.log(selected_action_probs) * returns).mean()

        # Update policy
        self.optimizer.zero_grad()
        loss.backward()
        self.optimizer.step()

        # Clear episode buffer
        episode_return = sum(self.episode_rewards)
        self.episode_states.clear()
        self.episode_actions.clear()
        self.episode_rewards.clear()

        return {
            'loss': loss.item(),
            'episode_return': episode_return
        }

    def _compute_returns(self, rewards: List[float]) -> np.ndarray:
        """Compute discounted returns for each timestep.

        Args:
            rewards: List of rewards from episode

        Returns:
            Array of returns (same length as rewards)
        """
        returns = []
        G = 0

        # Compute returns backwards (from end of episode)
        for reward in reversed(rewards):
            G = reward + self.gamma * G
            returns.insert(0, G)

        return np.array(returns, dtype=np.float32)

    def save(self, path: str):
        """Save agent to disk."""
        torch.save({
            'policy_state_dict': self.policy.state_dict(),
            'optimizer_state_dict': self.optimizer.state_dict(),
        }, path)

    def load(self, path: str):
        """Load agent from disk."""
        checkpoint = torch.load(path)
        self.policy.load_state_dict(checkpoint['policy_state_dict'])
        self.optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
